OBJS = main.o Shell.o FileSystem.o IOSystem.o
CC = g++
DEBUG = -g
CFLAGS = -Wall -c $(DEBUG)
LFLAGS = -Wall $(DEBUG)

all: ics53_project1

ics53_project1 : $(OBJS)
	$(CC) $(OBJS) -o ics51_project1

main.o : main.cpp Shell.o
	$(CC) $(CFLAGS) main.cpp

Shell.o : Shell.cpp Shell.hpp FileSystem.hpp IOSystem.hpp
	$(CC) $(CFLAGS) Shell.cpp

FileSystem.o : FileSystem.cpp FileSystem.hpp IOSystem.hpp
	$(CC) $(CFLAGS) FileSystem.cpp

IOSystem.o : IOSystem.cpp IOSystem.hpp
	$(CC) $(CFLAGS) IOSystem.cpp